### ISSUE TITLE
Remove white background on Gen I and Gen II sprites

### ISSUE THREAD

**Issue by Lancelotbronner** [PokeAPI/sprites#30]
Instead of having an (incomplete) transparent category, I feel like they should all already be.

Your background might not necessarily be white, so having to display a white square along with the sprite is just ugly in most cases.

If anyone has a magic script that could do that, it would be awesome! If not, I could volunteer to start removing white backgrounds and make a pull request once I'm done with either of the gens.

So what do you people think?

**Comment by C-Garza** [comment]
We agree that they should be transparent, we had a conversation about that [in this PR](https://github.com/PokeAPI/sprites/pull/18#issuecomment-666912853), but determined that it would be a lot of manual work to do them. So we ended up using images from [Smogon](https://play.pokemonshowdown.com/sprites/) where they already had at least the front images as transparent.

If you think you can make them transparent and make a PR I'm sure that'd be pretty useful. 😄
What do you think @Naramsim?

**Comment by Naramsim** [comment]
> Instead of having an (incomplete) transparent category, I feel like they should all already be.
> 
> Your background might not necessarily be white, so having to display a white square along with the sprite is just ugly in most cases.
> 
> If anyone has a magic script that could do that, it would be awesome! If not, I could volunteer to start removing white backgrounds and make a pull request once I'm done with either of the gens.
> 
> So what do you people think?

Hi @Lancelotbronner, our collection of gen-i and gen-ii transparent sprites is complete but some pokemon have still white portions inside, am I right?

For example, Gastly, Muk... all those sprites aren't perfect and some white background should be removed. Both @C-Garza and @magical tried developing some ImageMagick scripts but in the end it was too difficult to make it work.

If you volunteer to help us, we will accept any contribution happily. If so, I would ask you to modify and improve all the transparent sprites we already have (those in the `/transparent` folders).

After your help, we could even share the sprites with Smogon and they could use them in their Pokemon Showdown battle game.

**Comment by Lancelotbronner** [comment]
Hi @Naramsim,

> our collection of gen-i and gen-ii transparent sprites is complete but some pokemon have still white portions inside, am I right?
Not quite, I meant missing:
- gen ii gold has back, shiny and back-shiny but transparent only has front
- gen ii silver has back, shiny and back-shiny but transparent only has front
- gen i red-blue has back, gray and back-gray but transparent only has front
- gen i yellow has back, gbc, gray, back-gbc, back-gray but transparent only has front/back

I didn't find issues with the ones that are already transparent. My goal would be to stay consistent with the rest of the sprites in the repository which are already transparent.

So what I had in mind is to make all sprites transparent, and we could eventually remove the `/transparent` folder.

**Comment by Naramsim** [comment]
Got it. So the official sprites ripped from the game have the white border, so we will keep them as they are now. We could add the transparent version (in the `/transparent` folder) for the back, shiny, ... stuff. 

I think it's better to keep and also serve the original ones (white ones) because they are in fact original :)

So if you're still interested in adding all the transparent variants, feel free to open a PR. Even more, if you'd like to improve the current transparent sprites we have.

**Comment by C-Garza** [comment]
I noticed that Smogon actually added transparent sprites for `gen i` and `gen-ii` and fixed up some errors in the `front` ones as well. You can see them [here](https://play.pokemonshowdown.com/sprites/). An example, here is [Gastly](https://play.pokemonshowdown.com/sprites/gen1-back/gastly.png). The only difference I see is that their `back` sprites are 96x96 compared to our 32x32.

Actually, looking at the `front` sprites of both `gen-i` and `gen-ii` they are pretty inconsistent in size. But I remember getting those images from Veekun so I guess they just are like that?

Anyway, I see that all the transparent images we currently have for these two gen's are the Smogon ones, which are 96x96, so I think we should keep these new `back` transparent images as 96x96 as well, since they are already modified just by adding transparency. I can start adding them sometime this week.

I was curious how they did it, and I came across [this thread](https://www.smogon.com/forums/threads/fix-mews-rby-sprite-fix-on-post-3-like-30-others-post-4-more-things-thereafter.3672321/). I guess this user May did them all by hand, at least the `gen-i` ones. Amazing!

**Comment by Naramsim** [comment]
Hi @C-Garza, thanks for looking into it :)  Did they update all the sprites at [this](https://play.pokemonshowdown.com/sprites/) index? Because we could download them all, adapt [the script](https://github.com/PokeAPI/sprites/blob/master/scripts/renameSmogon.sh) we made, and update the sprites in this repo. 

A note: I'm talking only about updating the images in our `transparent/` folders.

**Comment by C-Garza** [comment]
Yeah they did from what it looks like at the upload date and looking through a couple of the sprites.

So for `gen-i`, we need to get their [`gen1-back`](https://play.pokemonshowdown.com/sprites/gen1-back/) and [`gen1`](https://play.pokemonshowdown.com/sprites/gen1/), those are both `yellow` version. We also need [`gen1rb`](https://play.pokemonshowdown.com/sprites/gen1rb/) and [`gen1rgb-back`](https://play.pokemonshowdown.com/sprites/gen1rgb-back/), those are for `red` and `blue`.

The `gen-ii` ones look fine, they actually haven't been updated. It's just that they still don't have `shiny` or `back` for `gold` and `silver` still, so those two versions will be the only ones missing `transparent` sprites still.

**Comment by C-Garza** [comment]
Now the only missing transparent ones are `silver` and `gold`. Those two only have `front-transparent` available to them.
