### ISSUE TITLE
Spirites image qualities.

### ISSUE THREAD

**Issue by danny329** [PokeAPI/sprites#48]
Most of the pokemon spirities are of low quality. and are not usable because of the. can we upgrade the spirites images.

**Comment by Naramsim** [comment]
Hi, which sprites are you referring to? Can you post an example?

**Comment by danny329** [comment]
Hi, It's actually all the spirites. Most of them are 80x80 png images. Which looks good only on smaller screens.On Jun 21, 2021 1:22 PM, Alessandro Pezzè ***@***.***> wrote:
Hi, which sprites are you referring to? Can you post an example?

**Comment by Naramsim** [comment]
In our repo we have 45310 files of different sizes. These files were mostly scraped off ROMs and that's why their size is small. 

If you are unhappy with their resolution you can pick the sprites for a specific version or the sprites in the `other` folder. Or suggest us a place where we can find sprites with an higher resolution

**Comment by danny329** [comment]
Hi, so i found lots of good quality spirities from https://archives.bulbagarden.net/wiki/Category:Bulbasaur. We will have to cherry pick good images from there.

**Comment by Naramsim** [comment]
An example:

To me they seem to have the very same size as ours:

https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png
https://archives.bulbagarden.net/media/upload/0/03/001.png

**Comment by azzamsa** [comment]
@danny329 I use the images here https://github.com/PokeAPI/sprites/tree/master/sprites/pokemon/other/, for hi-def images.
